import { describe, expect, test } from "bun:test";
import { parseLockfile, stripJsonComments, stripTrailingCommas } from "../src/scanner/lockfile";

const BUN_LOCK = `{
  "lockfileVersion": 2,
  "configVersion": 1,
  "workspaces": {
    "": {
      "name": "app",
      "dependencies": {
        "left-pad": "^1.3.0",
      },
    },
  },
  "packages": {
    "left-pad": ["left-pad@1.3.0", "", {}, "sha512-aaa"],
    "@scope/tool": ["@scope/tool@2.1.0", "", { "bin": { "tool": "bin/tool" } }, "sha512-bbb"],
    "aliased": ["aliased@npm:real@4.5.6", "", {}, "sha512-ccc"],
    "unversioned": ["unversioned@workspace:."],
  },
}
`;

const NPM_LOCK = JSON.stringify({
  name: "app",
  lockfileVersion: 3,
  packages: {
    "": { name: "app", dependencies: { sharp: "^0.32.0" } },
    "node_modules/sharp": { version: "0.32.6", hasInstallScript: true },
    "node_modules/left-pad": { version: "1.3.0", dev: true },
    "node_modules/a/node_modules/dup": { version: "2.0.0" },
    "node_modules/@scope/pkg": { version: "3.0.0", optional: true },
  },
});

const YARN_V1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"left-pad@^1.3.0":
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz#abc"

"@scope/pkg@^3.0.0", "@scope/pkg@^3.1.0":
  version "3.0.0"
  resolved "https://registry.yarnpkg.com/@scope/pkg/-/pkg-3.0.0.tgz#def"
  dependencies:
    left-pad "^1.3.0"
`;

const YARN_BERRY = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10

"left-pad@npm:^1.3.0":
  version: 1.3.0
  resolution: "left-pad@npm:1.3.0"
`;

const PNPM_LOCK = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true

importers:
  .:
    dependencies:
      left-pad:
        specifier: ^1.3.0
        version: 1.3.0

packages:

  left-pad@1.3.0:
    resolution: {integrity: sha512-aaa}

  '@scope/pkg@3.0.0':
    resolution: {integrity: sha512-bbb}
    requiresBuild: true

  /legacy@1.0.0:
    resolution: {integrity: sha512-ccc}
`;

describe("JSONC helpers", () => {
  test("strips line and block comments but not string contents", () => {
    const source = '{\n // note\n "url": "https://x.test/a/*b*/",\n /* block */ "n": 1\n}';
    expect(JSON.parse(stripJsonComments(source))).toEqual({ url: "https://x.test/a/*b*/", n: 1 });
  });

  test("strips trailing commas but not commas inside strings", () => {
    expect(stripTrailingCommas('{"a": [1, 2,], "b": "x,",}')).toBe('{"a": [1, 2], "b": "x,"}');
  });
});

describe("bun.lock", () => {
  test("reads name@version and tolerates JSONC", () => {
    const result = parseLockfile("bun", BUN_LOCK);
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value.kind).toBe("bun");
      expect(result.value.lockfileVersion).toBe("2");
      expect(result.value.packages.map((pkg) => `${pkg.name}@${pkg.version}`)).toEqual([
        "@scope/tool@2.1.0",
        "aliased@4.5.6",
        "left-pad@1.3.0",
      ]);
    }
  });

  test("records no install-script evidence, because the format carries none", () => {
    const result = parseLockfile("bun", BUN_LOCK);
    expect(result.ok && result.value.packages.every((pkg) => !pkg.installScript)).toBe(true);
  });
});

describe("package-lock.json", () => {
  test("reads v3 packages, including dev, optional and install-script flags", () => {
    const result = parseLockfile("npm", NPM_LOCK);
    expect(result.ok).toBe(true);
    if (result.ok) {
      const byName = new Map(result.value.packages.map((pkg) => [pkg.name, pkg]));
      expect(byName.get("sharp")?.installScript).toBe(true);
      expect(byName.get("left-pad")?.dev).toBe(true);
      expect(byName.get("dup")?.version).toBe("2.0.0");
      expect(byName.get("@scope/pkg")?.optional).toBe(true);
      expect(byName.get("@scope/pkg")?.version).toBe("3.0.0");
    }
  });

  test("reads the legacy v1 nested dependencies", () => {
    const legacy = JSON.stringify({
      lockfileVersion: 1,
      dependencies: { a: { version: "1.0.0", dependencies: { b: { version: "2.0.0" } } } },
    });
    const result = parseLockfile("npm", legacy);
    expect(result.ok && result.value.packages.map((pkg) => `${pkg.name}@${pkg.version}`)).toEqual([
      "a@1.0.0",
      "b@2.0.0",
    ]);
  });

  test("fails loudly on invalid JSON", () => {
    const result = parseLockfile("npm", "{");
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("E_PARSE");
      expect(result.error.hint).toBeDefined();
    }
  });
});

describe("yarn.lock", () => {
  test("reads v1 blocks and picks the name out of a multi-pattern header", () => {
    const result = parseLockfile("yarn", YARN_V1);
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value.lockfileVersion).toBe("1");
      expect(result.value.packages.map((pkg) => `${pkg.name}@${pkg.version}`)).toEqual([
        "@scope/pkg@3.0.0",
        "left-pad@1.3.0",
      ]);
    }
  });

  test("reads berry blocks and its metadata version", () => {
    const result = parseLockfile("yarn", YARN_BERRY);
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value.lockfileVersion).toBe("8");
      expect(result.value.packages.map((pkg) => pkg.version)).toEqual(["1.3.0"]);
    }
  });
});

describe("pnpm-lock.yaml", () => {
  test("reads package keys, the quoted form, the legacy leading slash and requiresBuild", () => {
    const result = parseLockfile("pnpm", PNPM_LOCK);
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value.lockfileVersion).toBe("9.0");
      const byName = new Map(result.value.packages.map((pkg) => [pkg.name, pkg]));
      expect(byName.get("left-pad")?.version).toBe("1.3.0");
      expect(byName.get("@scope/pkg")?.installScript).toBe(true);
      expect(byName.get("legacy")?.version).toBe("1.0.0");
    }
  });

  test("fails loudly when there is no packages section", () => {
    const result = parseLockfile("pnpm", "lockfileVersion: '9.0'\n");
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("E_PARSE");
    }
  });
});
